FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Instalar Doxygen y herramientas para C++
RUN apt-get update && apt-get install -y \
    doxygen \
    doxygen-doc \
    doxygen-gui \
    graphviz \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-fonts-recommended \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /project/docs

ENTRYPOINT ["doxygen"]
